### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nicollaas94** [Saliba/WelcomePack#1]
https://github.com/Saliba/WelcomePack/wiki/driver-license

the **CBR website** link is broken
I guess the right one is
https://www.cbr.nl/nl/rijbewijs-halen/auto/gezondheidsverklaring-autorijbewijs.htm

but I'm not sure

**Comment by Saliba** [comment]
Great Nicollas, I have fixed it.

Thank you
Lucas Saliba
